### PR TITLE
Add proteowizard

### PR DESCRIPTION
**Pull request by asmaahassan90**
after merge, URL needs to be changed again.

### CODE REVIEW

**Comment by antoniokaust** [comment]
How come we have to store the ZIP here?

**Comment by asmaahassan90** [comment]
Well, there is no direct link to it. Had to upload it somewhere. So it was Nasr's suggestion to add it with the formula.
Do you suggest elsewhere? maybe we can create a repo for all softwares with no direct download links.

**Comment by antoniokaust** [comment]
I think it's a good idea to keep it in GitHub. This allows other people to fork/clone our repo.

**Comment by antoniokaust** [comment]
Asmaa you have to

- change URL & corresponding sha256 sum.
- change permissions to 644
- test one more time on CentOS 6.x & Ubunut 16

**Pull request merged**
